// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBr3diWGMXHzNv3KbQN0ln1_hb2nad_oU',
    appId: '1:111391263670:web:d5bac8b5a03eedf1b98f17',
    messagingSenderId: '111391263670',
    projectId: 'librarymanagementsystem-f3c40',
    authDomain: 'librarymanagementsystem-f3c40.firebaseapp.com',
    storageBucket: 'librarymanagementsystem-f3c40.firebasestorage.app',
    measurementId: 'G-VFRP4WTDEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogJ16fZnK6rGDieG_SCA0HF-NNXLqgVw',
    appId: '1:111391263670:android:ca25683bfda59193b98f17',
    messagingSenderId: '111391263670',
    projectId: 'librarymanagementsystem-f3c40',
    storageBucket: 'librarymanagementsystem-f3c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwf5RWOTkUUtQot6jyhd_lNB74kyawZbw',
    appId: '1:111391263670:ios:38154c263b3a191fb98f17',
    messagingSenderId: '111391263670',
    projectId: 'librarymanagementsystem-f3c40',
    storageBucket: 'librarymanagementsystem-f3c40.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwf5RWOTkUUtQot6jyhd_lNB74kyawZbw',
    appId: '1:111391263670:ios:38154c263b3a191fb98f17',
    messagingSenderId: '111391263670',
    projectId: 'librarymanagementsystem-f3c40',
    storageBucket: 'librarymanagementsystem-f3c40.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBr3diWGMXHzNv3KbQN0ln1_hb2nad_oU',
    appId: '1:111391263670:web:f3f6cf9455da63d9b98f17',
    messagingSenderId: '111391263670',
    projectId: 'librarymanagementsystem-f3c40',
    authDomain: 'librarymanagementsystem-f3c40.firebaseapp.com',
    storageBucket: 'librarymanagementsystem-f3c40.firebasestorage.app',
    measurementId: 'G-D753WZYJLX',
  );

}